# Generated by Django 6.0 on 2025-12-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_order_customer_email_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='Payment_number',
            field=models.IntegerField(default='254792390205', max_length=20),
            preserve_default=False,
        ),
    ]
