# Generated by Django 6.0 on 2025-12-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_suppliers_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='Payment_number',
            field=models.CharField(max_length=20),
        ),
    ]
