# Generated by Django 6.0 on 2025-12-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_ordermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
